spring:
  application:
    name: procjena-rizika


  datasource:
    url: jdbc:mysql://localhost:3306/rizik_db
    username: root
    password: nikola2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    error:
      include-message: always
      include-binding-errors: always

jwt:
  secret: "my-secret-key my-secret-key my-secret-key"
  ttl: 30
  refresh: 90
